services:
  - type: web
    name: techstore-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_DB
        value: techstore
      - key: MONGODB_URI
        sync: false
      - key: CORS_ORIGIN
        sync: false
